[package]
name = "mildew"
version = "0.1.0"
authors = ["rap2hpoutre <raphaelht@gmail.com>"]
licence = "MIT"
description = "Rust helpers"
repository = "https://github.com/rap2hpoutre/mildew"

[dependencies]
hyper = "0.9"